name = "pole-rocks"
compatibility_date = "2024-09-02"
node_compat = true

# Local 
d1_databases = [
	{ binding = "DB", database_name = "local_pole-rocks", database_id = "n/a", migrations_dir = "src/lib/server/db/migrations" },
]

[env.preview]
d1_databases = [
	{ binding = "DB", database_name = "staging_pole-rocks", database_id = "d1814951-06ff-4a12-848f-97436c6a85b0", migrations_dir = "src/lib/server/db/migrations" },
]

[env.production]
d1_databases = [
	{ binding = "DB", database_name = "pole-rocks", database_id = "5c232b69-8d83-4f23-abdc-4c199ff8dc66", migrations_dir = "src/lib/server/db/migrations" },
]
