name: Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format
    uses: ./.github/workflows/ci-build.yml
    with:
      run: |
        npm run format
  lint:
    name: Lint
    uses: ./.github/workflows/ci-build.yml
    with:
      run: |
        npm run lint
  check:
    name: Check
    uses: ./.github/workflows/ci-build.yml
    with:
      run: |
        npm run check
