name: Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  ci-build:
    name: CI Build
    uses: ./.github/workflows/ci-build.yml
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Format
        run: npm run format

  # lint:
  #   name: Lint
  #   uses: ./.github/workflows/ci-build.yml
  #   with:
  #     run: |
  #       npm run lint
  # check:
  #   name: Check
  #   uses: ./.github/workflows/ci-build.yml
  #   with:
  #     run: |
  #       npm run check
