name: Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/ci-build.yml
      - name: Format
        run: |
          npm run format
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/ci-build.yml
      - name: Lint
        run: |
          npm run lint
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/ci-build.yml
      - name: Check
        run: |
          npm run check
