name: Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  ci-build:
    name: CI Build
    uses: ./.github/workflows/ci-build.yml
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Format
        run: |
          npm run format
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Lint
        run: |
          npm run lint
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Check
        run: |
          npm run check
