name: Lint

on:
  push:
  pull_request:
    branches: [main]

jobs:
  ci-build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clean Install
        run: |
          npm ci
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Format
        run: |
          npm run format
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Lint
        run: |
          npm run lint
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: Check
        run: |
          npm run check
