name: Tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    environment: Staging
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Clean Install
        run: npm ci
      - name: Tests
        run: npm run test:unit -- run

  e2e-tests:
    name: e2e Tests
    runs-on: ubuntu-latest
    environment: Staging
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Clean Install
        run: npm ci
      - name: Tests
        run: |
          npx playwright install --with-deps
          npm run test:e2e

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
